sudo: required
services:
  - docker

before_install:
  - docker build -t vinothrallapalli/reatc-test -f ./web/Dockerfile.dev ./web

script:
  - docker run vinothrallapalli npm run test -- --coverage

after_success:
  - docker build -t vinothrallapalli/multi-web ./web
  - docker build -t vinothrallapalli/multi-nginx ./nginx
  - docker build -t vinothrallapalli/multi-api ./api
  - docker build -t vinothrallapalli/multi-worker ./worker

# Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push vinothrallapalli/multi-web
  - docker push vinothrallapalli/multi-nginx
  - docker push vinothrallapalli/multi-api
  - docker push vinothrallapalli/multi-worker
